### ISSUE TITLE
Anki 2.1.45 compatibility (special case)

### ISSUE THREAD

**Issue by rwmpelstilzchen** [rjgoif/anki-bury-future-sibs#4]
Hi,

Thanks for this plug-in! It has changed the way I learn new stuff with Anki and IMHO a similar option should be incorporated as a built-in feature.

I use [this trick](https://www.reddit.com/r/Anki/comments/8by2il/) for automatic volume control.

Yesterday I have installed the new version of Anki (2.1.45) and now I get this error message when hitting <kbd>shift</kbd>+<kbd>b</kbd>:

    Error 
    An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
    If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
    When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
    Debug info:
    Anki 2.1.45 (355e66e8) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
    Platform: Linux
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2021-08-03 17:02:19
    Add-ons possibly involved: ⁨bury future new sibs⁩
    
    Caught exception:
    Traceback (most recent call last):
      File "/home/me/.local/share/Anki2/addons21/930365039/bury_ahead.py", line 97, in buryNewSibsMenu
        conf = mw.col.decks.confForDid(did)
      File "anki/_legacy.py", line 55, in __getattr__
      File "anki/_legacy.py", line 37, in _print_warning
      File "anki/_legacy.py", line 33, in print_deprecation_warning
    OSError: [Errno 5] Input/output error

If I run Anki without the said PulseAudio trick everything works fine.

**Comment by rwmpelstilzchen** [comment]
(solved by https://github.com/rjgoif/anki-bury-future-sibs/pull/5)

**Comment by rwmpelstilzchen** [comment]
I reopen this as the changes have not been merged. In fact, there seems to be no activity on this repo…
